server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zemolxe
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  influx:
    url: http://localhost:8086
    token: your-influxdb-token
    org: zemolxe
    bucket: energy-data